- .gitignore
- form/index.js
- notifications/index.js
- notifications/webhook.js
- package.json
- routes/components/form.js
> Feature #5 webhooks

- public/js/form.js
> Update required field only if input is visible

- public/js/form.js
> Feature #14 visibility and or

- form/index.js
- public/js/form.js
- views/mixins/fields.pug
> Added timefield support

- .gitignore
- form/index.js
- views/mixins/fields.pug
> Added select fied support

- public/js/form.js
> Feature #34 visible if true other fields

- public/js/form.js
> Register change listeners for find only once with each root rule

- form/index.js
> Validate visible-if rules also on backend

- .gitignore
- index.js
- package.json
- routes/index.js
- views/mixins/admin.pug
> Added keycloak support

- .gitignore
- form/index.js
- index.js
- routes/components/admin.js
- routes/index.js
- test/test-utils.js
> Feature #41 targeted forms

- .gitignore
- .travis.yml
- form/index.js
- index.js
- package.json
- routes/components/admin.js
- routes/index.js
- test/administrator-tests.js
- test/append-function-test.js
- test/datepicker-test.js
- test/email-tests.js
- test/form-field-test.js
- test/test-utils.js
- test/webhook-test.js
- travis.sh
- views/mixins/admin.pug
> Added websocket support

- public/js/form.js
- routes/index.js
- scss/form.scss
- test/administrator-tests.js
- test/append-function-test.js
- test/datepicker-test.js
- test/email-tests.js
- test/form-field-test.js
- test/webhook-test.js
- views/form.pug
> Added modal after successful form post

- notifications/client-email.js
- notifications/index.js
- notifications/manager-email.js
- package.json
- routes/components/form.js
- test/data/email-form.json
> Feature #45 targeted notifications

- form/index.js
- notifications/manager-email.js
> Added support for targeting managers with boolean fields

- form/index.js
- routes/components/admin.js
> Fixed bug which caused form status not updateable

- package.json
- routes/components/admin.js
- views/form-reply-print.pug
- views/form-reply.pug
- views/mixins/fields.pug
> Feature #65 pdf export

- form/index.js
- public/js/formUtils.js
- views/mixins/fields.pug
> Added support for constraints in date fields

- form/index.js
> Compare to start of day

- form/index.js
> Delete values from fields that are not supposed to be visible

- form/index.js
> changed server side validation to look for correct rule property
